version: '3.6'

services:
  db:
    image: mysql:5.7
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      
  sagacity-dev:
    build: ./sagacity
    hostname: sagacity-dev
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./sagacity:/var/www/html